"""empty message

Revision ID: 14b483ab7c80
Revises: 
Create Date: 2020-02-13 15:55:24.926061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '14b483ab7c80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_info',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('os_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('os_version', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('app_version', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('build_version', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('model_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('model_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fcm_token', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='device_info_pkey')
    )
    # ### end Alembic commands ###
