"""Update is_verified, password column to email_verified, password_hash

Revision ID: 2be6401be738
Revises: 9783911731b2
Create Date: 2020-04-24 17:52:42.525073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2be6401be738'
down_revision = '9783911731b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.drop_column('user', 'is_varified')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=355), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_varified', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'email_verified')
    # ### end Alembic commands ###
