"""empty message

Revision ID: 368d38a141ce
Revises: 7aedd9d48998
Create Date: 2020-02-19 11:58:37.033250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368d38a141ce'
down_revision = '7aedd9d48998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_image_url')
    # ### end Alembic commands ###
