"""empty message

Revision ID: 63cc08e2605b
Revises: 838ed225a574
Create Date: 2020-02-18 11:50:17.693538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63cc08e2605b'
down_revision = '838ed225a574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_password_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_password_key', 'user', ['password'])
    # ### end Alembic commands ###
