"""empty message

Revision ID: 7fd7e28a3348
Revises: ec7ada05c116
Create Date: 2020-02-14 13:06:56.226360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fd7e28a3348'
down_revision = 'ec7ada05c116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    # ### end Alembic commands ###
